---
- name: Find QRadar rule state
  hosts: all
  collections:
    - ibm.qradar

  tasks:
    - name: get info about qradar rule
      ibm.qradar.rule_info:
        name: "Potential DDoS Against Single Host (TCP)"
